// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAJmDGktqdRd9p4WUF_kHsKqKwOyOU_fQ',
    appId: '1:448244556927:web:c5c4b58284c8bdd2710b4a',
    messagingSenderId: '448244556927',
    projectId: 'deployment-bd870',
    authDomain: 'deployment-bd870.firebaseapp.com',
    storageBucket: 'deployment-bd870.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAReNFC-X5l6aL4CETilGEcqMXKUAO5NdY',
    appId: '1:448244556927:android:a87297cdd5a80e37710b4a',
    messagingSenderId: '448244556927',
    projectId: 'deployment-bd870',
    storageBucket: 'deployment-bd870.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE5SQBg4C-d-Xzq6Wlqlq5oAmFpueISt8',
    appId: '1:448244556927:ios:e5b84e899f00e619710b4a',
    messagingSenderId: '448244556927',
    projectId: 'deployment-bd870',
    storageBucket: 'deployment-bd870.firebasestorage.app',
    iosBundleId: 'com.example.hsbKurir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE5SQBg4C-d-Xzq6Wlqlq5oAmFpueISt8',
    appId: '1:448244556927:ios:e5b84e899f00e619710b4a',
    messagingSenderId: '448244556927',
    projectId: 'deployment-bd870',
    storageBucket: 'deployment-bd870.firebasestorage.app',
    iosBundleId: 'com.example.hsbKurir',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAJmDGktqdRd9p4WUF_kHsKqKwOyOU_fQ',
    appId: '1:448244556927:web:75f0322206d82625710b4a',
    messagingSenderId: '448244556927',
    projectId: 'deployment-bd870',
    authDomain: 'deployment-bd870.firebaseapp.com',
    storageBucket: 'deployment-bd870.firebasestorage.app',
  );
}
